name: 🚀 Deploy API Gateway to AWS

on:
  push:
    paths:
      - 'api-gateway/**'
    branches:
      - TestConectionProducts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📦 Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest \
            -f api-gateway/Dockerfile api-gateway/
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Deploy API Gateway to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST_API_GATEWAY }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "🔍 Checking if Docker is installed..."
          if ! command -v docker &> /dev/null; then
            echo "📦 Installing Docker..."
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
          fi

          echo "🛑 Stopping previous container..."
          sudo docker stop api-gateway || true
          sudo docker rm api-gateway || true

          echo "🧹 Removing old Docker images..."
          sudo docker image prune -af

          echo "📥 Pulling the latest Docker image..."
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

          echo "🚀 Running the new container..."
          sudo docker run -d \
            --name api-gateway \
            -p ${{ secrets.SERVER_PORT_API_GATEWAY }}:${{ secrets.SERVER_PORT_API_GATEWAY }} \
            -e SERVER_PORT=${{ secrets.SERVER_PORT_API_GATEWAY }} \
            --restart=always \
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

          echo "🔍 Verifying deployment..."
          if sudo docker ps -f name=api-gateway | grep api-gateway; then
            echo "✅ Deployment successful: API Gateway is running."
          else
            echo "❌ Deployment failed: Check logs for errors."
            exit 1
          fi 

    - name: 🔐 Log out of Docker Hub
      run: docker logout
