name: CI/CD for API Gateway

on:
  push:
    paths:
      - 'api-gateway/**'
    branches: 
    - TestConectionProducts

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          docker build api-gateway/. -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API Gateway to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_API_GATEWAY }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop api-gateway || true
            sudo docker rm api-gateway || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
            sudo docker run -d --name api-gateway -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
