name: CI/CD for API Gateway

on:
  push:
    paths:
      - 'api-gateway/**'
      - 'Backend_uceShoes/productManagement/**'
      - 'Backend_uceShoes/productSearchGraphQL/**'
    branches: ["PENDIENTE"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          docker build api-gateway/. \
            --build-arg POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --build-arg POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} \
            --build-arg POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
            --build-arg MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            --build-arg MYSQL_USER=${{ secrets.MYSQL_USER }} \
            --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            --build-arg MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
            --build-arg MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
            -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API Gateway to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_API_GATEWAY }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop api-gateway || true
            sudo docker rm api-gateway || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
            sudo docker run -d --name api-gateway -p 8080:8080 \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
              -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
              -e MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
              ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
