name: 🚀 Deploy Category Update Service to AWS

on:
  push:
    paths:
      - 'Backend_uceShoes/productManagement/productCreation/Category/updateCategory/**'
    branches:
      - main

jobs:
  build-and-push:
    name: 📦 Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📦 Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/category-update:latest \
            -f Backend_uceShoes/productManagement/productCreation/Category/updateCategory/Dockerfile \
            Backend_uceShoes/productManagement/productCreation/Category/updateCategory

          docker push ${{ secrets.DOCKER_USERNAME }}/category-update:latest

  deploy:
    name: 🚀 Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: 🚀 Connect to EC2 and Deploy Category Update Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_UPDATE_CATEGORY }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🔍 Checking if Docker is installed..."
            if ! command -v docker &> /dev/null; then
              echo "📦 Installing Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo usermod -a -G docker $USER
            fi

            echo "🔍 Checking if netcat (nc) is installed..."
            if ! command -v nc &> /dev/null; then
              echo "📦 Installing netcat..."
              sudo yum install -y nc
            fi

            echo "🛑 Stopping and removing previous container..."
            sudo docker stop category-update || true
            sudo docker rm category-update || true

            echo "🧹 Removing old Docker images..."
            sudo docker image prune -af

            echo "📥 Pulling the latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/category-update:latest

            echo "🔍 Verifying database connection before running the container..."
            if ! nc -zv ${{ secrets.POSTGRES_HOST }} ${{ secrets.POSTGRES_PORT }}; then
              echo "❌ Database connection failed. Deployment aborted."
              exit 1
            fi

            echo "🚀 Running the new container..."
            sudo docker run -d \
              --name category-update \
              -p ${{ secrets.SERVER_PORT_UPDATE_CATEGORY }}:${{ secrets.SERVER_PORT_UPDATE_CATEGORY }} \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -e DB_DIALECT=postgres \
              ${{ secrets.DOCKER_USERNAME }}/category-update:latest

            echo "🔍 Verifying deployment..."
            sleep 5
            if [ "$(sudo docker ps -q -f name=category-update)" ]; then
              echo "✅ Deployment successful: Category Update Service is running."
            else
              echo "❌ Deployment failed: Checking logs..."
              sudo docker logs category-update
              echo "⚠️ Checking Docker container status..."
              sudo docker ps -a
              exit 1
            fi
