name: CI/CD for Category Services

on:
  push:
    paths:
      - 'Backend_uceShoes/productManagement/Category/**'
    branches: ["PENDIENTE"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker images
        run: |
          for service in createCategory deleteCategory getAllCategories getCategoryById updateCategory; do
            docker build Backend_uceShoes/productManagement/Category/$service/. \
              --build-arg POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              --build-arg POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} \
              --build-arg POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -t ${{ secrets.DOCKER_USERNAME }}/$service:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
          done

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_CATEGORIES }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            for service in createCategory deleteCategory getAllCategories getCategoryById updateCategory; do
              sudo docker stop $service || true
              sudo docker rm $service || true
              sudo docker pull ${{ secrets.DOCKER_USERNAME }}/$service:latest
              sudo docker run -d --name $service -p 3005:3005 \
                -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
                -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
                -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                -e POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} \
                -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
                ${{ secrets.DOCKER_USERNAME }}/$service:latest
            done
