name: 🚀 Deploy Category Create Service to AWS

on:
  push:
    paths:
      - 'Backend_uceShoes/productManagement/productCreation/Category/createCategory/**'
    branches:
      - TestConectionProducts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🔧 Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Iniciar sesión en Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📦 Construir y subir imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/category-create:latest \
            -f Backend_uceShoes/productManagement/productCreation/Category/createCategory/Dockerfile \
            Backend_uceShoes/productManagement/productCreation/Category/createCategory

          docker push ${{ secrets.DOCKER_USERNAME }}/category-create:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: 🚀 Connect to EC2 and Deploy Category Create Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_CREATE_CATEGORY }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🔍 Checking if Docker is installed..."
            if ! command -v docker &> /dev/null; then
              echo "📦 Installing Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo usermod -a -G docker $USER
            fi

            echo "🛑 Stopping and removing previous container..."
            if sudo docker ps -q -f name=category-create; then
              sudo docker stop category-create
              sudo docker rm category-create
            else
              echo "⚠️ No running container found."
            fi

            echo "🧹 Removing old Docker images..."
            sudo docker image prune -af || echo "⚠️ No images to remove."

            echo "📥 Pulling the latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/category-create:latest

            echo "🔎 Checking required environment variables..."
            REQUIRED_VARS=(POSTGRES_HOST POSTGRES_PORT POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB SERVER_PORT_CREATE_CATEGORY)
            for VAR in "${REQUIRED_VARS[@]}"; do
              if [[ -z "${!VAR}" ]]; then
                echo "❌ ERROR: Required environment variable $VAR is not set."
                exit 1
              fi
            done

            echo "🚀 Running the new container..."
            sudo docker run -d \
              --name category-create \
              -p ${{ secrets.SERVER_PORT_CREATE_CATEGORY }}:${{ secrets.SERVER_PORT_CREATE_CATEGORY }} \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/category-create:latest

            echo "🔍 Verifying deployment..."
            sleep 10  # Espera para asegurarse de que el contenedor inicie correctamente

            if sudo docker ps -q -f name=category-create | grep category-create; then
              echo "✅ Deployment successful: Category Create Service is running."
            else
              echo "❌ Deployment failed: Fetching logs..."
              sudo docker logs category-create
              exit 1
            fi

      - name: 🔐 Log out of Docker Hub
        run: docker logout
