name: CI/CD for GraphQL Service

on:
  push:
    paths:
      - 'Backend_uceShoes/productManagement/productSearchGraphQL/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📦 Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/graphql:latest Backend_uceShoes/productManagement/productSearchGraphQL
          docker push ${{ secrets.DOCKER_USERNAME }}/graphql:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_GRAPHQL }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "🔄 Stopping previous container if it exists..."
            sudo docker stop graphql || true
            sudo docker rm graphql || true

            echo "🧹 Cleaning up old Docker images..."
            sudo docker image prune -af

            echo "📥 Pulling the latest image from Docker Hub..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/graphql:latest

            echo "🔍 Checking if MySQL is reachable..."
            if ! nc -zv ${{ secrets.MYSQL_HOST }} ${{ secrets.MYSQL_PORT }}; then
              echo "❌ MySQL is not reachable. Deployment aborted."
              exit 1
            fi

            echo "🚀 Running the new container..."
            sudo docker run -d --name graphql \
              --restart=always \
              -p ${{ secrets.SERVER_PORT_GRAPHQL }}:${{ secrets.SERVER_PORT_GRAPHQL }} \
              -e DATABASE_URL="mysql+pymysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@${{ secrets.MYSQL_HOST }}:${{ secrets.MYSQL_PORT }}/product_search_development" \
              -e GRAPHQL_PORT=${{ secrets.SERVER_PORT_GRAPHQL }} \
              ${{ secrets.DOCKER_USERNAME }}/graphql:latest
