name: CI/CD for GraphQL Service

on:
  push:
    paths:
      - 'Backend_uceShoes/productSearchGraphQL/**'
    branches: ["PENDIENTE"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          docker build Backend_uceShoes/productSearchGraphQL/. \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --build-arg DB_USER=${{ secrets.DB_USER }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -t ${{ secrets.DOCKER_USERNAME }}/graphql:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/graphql:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_GRAPHQL }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop graphql || true
            sudo docker rm graphql || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/graphql:latest
            sudo docker run -d --name graphql \
              -p 3010:3010 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/graphql:latest
